#!/bin/sh
# This is a very simple script that tries to pull in dependencies from other
# repos. There are currently two dependencies: XHP and Hack's .hhi files. XHP's
# php-lib needs to go in the xhp directory, and Hack's hhi files need to go in
# the hhi file directory. If this script doesn't work for you, you can always
# clone these projects and copy the files yourself.

# Pull in the XHP files. These define the XHP classes that we need
rm -rf xhp
mkdir -p xhp
if type -p curl > /dev/null; then
  curl "https://raw.github.com/facebook/xhp/master/php-lib/core.php" -o "/tmp/xhp_core.php"
  curl "https://raw.github.com/facebook/xhp/master/php-lib/html.php" -o "/tmp/xhp_html.php"
  curl "https://raw.github.com/facebook/xhp/master/php-lib/init.php" -o "/tmp/xhp_init.php"
else
  wget -O /tmp/xhp_core.php https://raw.github.com/facebook/xhp/master/php-lib/core.php
  wget -O /tmp/xhp_html.php https://raw.github.com/facebook/xhp/master/php-lib/html.php
  wget -O /tmp/xhp_init.php https://raw.github.com/facebook/xhp/master/php-lib/init.php
fi

sed -e "s|<?php|<?hh // decl|" /tmp/xhp_core.php > xhp/core.php
sed -e "s|<?php|<?hh|" /tmp/xhp_html.php > xhp/html.php
sed -e "s|<?php|<?hh // strict |" /tmp/xhp_init.php > xhp/init.php
rm /tmp/xhp_core.php /tmp/xhp_html.php /tmp/xhp_init.php

# Pull in the hhi files. These define all the stdlib functions.

rm -rf hhi
if [ -d "/usr/share/hhvm/hack/hhi" ]; then
  cp -r /usr/share/hhvm/hack/hhi hhi
else
  git clone --depth 1 git@github.com:facebook/hhvm.git tmp_hhvm
  cp -rf tmp_hhvm/hphp/hack/hhi hhi
  rm -rf tmp_hhvm
fi
